// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/hominsu/slink/app/slink/service/internal/data/ent/schema"
	"github.com/hominsu/slink/app/slink/service/internal/data/ent/shortlink"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	shortlinkMixin := schema.ShortLink{}.Mixin()
	shortlinkMixinFields0 := shortlinkMixin[0].Fields()
	_ = shortlinkMixinFields0
	shortlinkMixinFields1 := shortlinkMixin[1].Fields()
	_ = shortlinkMixinFields1
	shortlinkFields := schema.ShortLink{}.Fields()
	_ = shortlinkFields
	// shortlinkDescCreatedAt is the schema descriptor for created_at field.
	shortlinkDescCreatedAt := shortlinkMixinFields0[0].Descriptor()
	// shortlink.DefaultCreatedAt holds the default value on creation for the created_at field.
	shortlink.DefaultCreatedAt = shortlinkDescCreatedAt.Default.(func() time.Time)
	// shortlinkDescUpdatedAt is the schema descriptor for updated_at field.
	shortlinkDescUpdatedAt := shortlinkMixinFields1[0].Descriptor()
	// shortlink.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	shortlink.DefaultUpdatedAt = shortlinkDescUpdatedAt.Default.(func() time.Time)
	// shortlink.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	shortlink.UpdateDefaultUpdatedAt = shortlinkDescUpdatedAt.UpdateDefault.(func() time.Time)
	// shortlinkDescExpireAt is the schema descriptor for expire_at field.
	shortlinkDescExpireAt := shortlinkFields[2].Descriptor()
	// shortlink.DefaultExpireAt holds the default value on creation for the expire_at field.
	shortlink.DefaultExpireAt = shortlinkDescExpireAt.Default.(func() time.Time)
	// shortlink.UpdateDefaultExpireAt holds the default value on update for the expire_at field.
	shortlink.UpdateDefaultExpireAt = shortlinkDescExpireAt.UpdateDefault.(func() time.Time)
}
