// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hominsu/slink/app/slink/service/internal/data/ent/predicate"
	"github.com/hominsu/slink/app/slink/service/internal/data/ent/shortlink"
)

// ShortLinkDelete is the builder for deleting a ShortLink entity.
type ShortLinkDelete struct {
	config
	hooks    []Hook
	mutation *ShortLinkMutation
}

// Where appends a list predicates to the ShortLinkDelete builder.
func (sld *ShortLinkDelete) Where(ps ...predicate.ShortLink) *ShortLinkDelete {
	sld.mutation.Where(ps...)
	return sld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sld *ShortLinkDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sld.sqlExec, sld.mutation, sld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sld *ShortLinkDelete) ExecX(ctx context.Context) int {
	n, err := sld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sld *ShortLinkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(shortlink.Table, sqlgraph.NewFieldSpec(shortlink.FieldID, field.TypeInt))
	if ps := sld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sld.mutation.done = true
	return affected, err
}

// ShortLinkDeleteOne is the builder for deleting a single ShortLink entity.
type ShortLinkDeleteOne struct {
	sld *ShortLinkDelete
}

// Where appends a list predicates to the ShortLinkDelete builder.
func (sldo *ShortLinkDeleteOne) Where(ps ...predicate.ShortLink) *ShortLinkDeleteOne {
	sldo.sld.mutation.Where(ps...)
	return sldo
}

// Exec executes the deletion query.
func (sldo *ShortLinkDeleteOne) Exec(ctx context.Context) error {
	n, err := sldo.sld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{shortlink.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sldo *ShortLinkDeleteOne) ExecX(ctx context.Context) {
	if err := sldo.Exec(ctx); err != nil {
		panic(err)
	}
}
