// @generated by protoc-gen-connect-es v1.2.0 with parameter "target=js+dts"
// @generated from file slink/service/v1/admin.proto (package slink.service.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { DeleteShortLinkRequest, ListShortLinkReply, ListShortLinkRequest } from "./admin_pb.js";

/**
 * @generated from service slink.service.v1.AdminService
 */
export const AdminService = {
  typeName: "slink.service.v1.AdminService",
  methods: {
    /**
     * @generated from rpc slink.service.v1.AdminService.FlushShortLink
     */
    flushShortLink: {
      name: "FlushShortLink",
      I: Empty,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc slink.service.v1.AdminService.ListShortLinks
     */
    listShortLinks: {
      name: "ListShortLinks",
      I: ListShortLinkRequest,
      O: ListShortLinkReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc slink.service.v1.AdminService.DeleteShortLink
     */
    deleteShortLink: {
      name: "DeleteShortLink",
      I: DeleteShortLinkRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
};

