// @generated by protoc-gen-es v1.6.0 with parameter "target=js+dts"
// @generated from file slink/service/v1/admin.proto (package slink.service.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message slink.service.v1.ListShortLinkRequest
 */
export const ListShortLinkRequest = proto3.makeMessageType(
  "slink.service.v1.ListShortLinkRequest",
  () => [
    { no: 1, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message slink.service.v1.ListShortLinkReply
 */
export const ListShortLinkReply = proto3.makeMessageType(
  "slink.service.v1.ListShortLinkReply",
  () => [
    { no: 1, name: "keys", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message slink.service.v1.DeleteShortLinkRequest
 */
export const DeleteShortLinkRequest = proto3.makeMessageType(
  "slink.service.v1.DeleteShortLinkRequest",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

