// @generated by protoc-gen-es v1.6.0 with parameter "target=js+dts"
// @generated from file slink/service/v1/error.proto (package slink.service.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * @generated from enum slink.service.v1.SLinkErrorReason
 */
export declare enum SLinkErrorReason {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: INTERNAL = 1;
   */
  INTERNAL = 1,

  /**
   * @generated from enum value: NOT_FOUND = 2;
   */
  NOT_FOUND = 2,

  /**
   * @generated from enum value: CONFLICT = 3;
   */
  CONFLICT = 3,

  /**
   * @generated from enum value: INVALID_ARGUMENT = 4;
   */
  INVALID_ARGUMENT = 4,

  /**
   * @generated from enum value: UNAUTHORIZED = 5;
   */
  UNAUTHORIZED = 5,

  /**
   * @generated from enum value: MOVED_PERMANENTLY = 6;
   */
  MOVED_PERMANENTLY = 6,
}

