// @generated by protoc-gen-es v1.6.0 with parameter "target=js+dts"
// @generated from file slink/service/v1/error.proto (package slink.service.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum slink.service.v1.SLinkErrorReason
 */
export const SLinkErrorReason = proto3.makeEnum(
  "slink.service.v1.SLinkErrorReason",
  [
    {no: 0, name: "UNKNOWN"},
    {no: 1, name: "INTERNAL"},
    {no: 2, name: "NOT_FOUND"},
    {no: 3, name: "CONFLICT"},
    {no: 4, name: "INVALID_ARGUMENT"},
    {no: 5, name: "UNAUTHORIZED"},
    {no: 6, name: "MOVED_PERMANENTLY"},
  ],
);

