// @generated by protoc-gen-connect-es v1.2.0 with parameter "target=js+dts"
// @generated from file slink/service/v1/site.proto (package slink.service.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { CountReply, PingReply } from "./site_pb.js";

/**
 * @generated from service slink.service.v1.SiteService
 */
export const SiteService = {
  typeName: "slink.service.v1.SiteService",
  methods: {
    /**
     * @generated from rpc slink.service.v1.SiteService.Ping
     */
    ping: {
      name: "Ping",
      I: Empty,
      O: PingReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc slink.service.v1.SiteService.Count
     */
    count: {
      name: "Count",
      I: Empty,
      O: CountReply,
      kind: MethodKind.Unary,
    },
  }
};

