// @generated by protoc-gen-es v1.6.0 with parameter "target=js+dts"
// @generated from file slink/service/v1/slink.proto (package slink.service.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message slink.service.v1.CreateShortLinkRequest
 */
export const CreateShortLinkRequest = proto3.makeMessageType(
  "slink.service.v1.CreateShortLinkRequest",
  () => [
    { no: 1, name: "link", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message slink.service.v1.CreateShortLinkReply
 */
export const CreateShortLinkReply = proto3.makeMessageType(
  "slink.service.v1.CreateShortLinkReply",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

