// @generated by protoc-gen-connect-es v1.2.0 with parameter "target=js+dts"
// @generated from file slink/service/v1/slink.proto (package slink.service.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateShortLinkReply, CreateShortLinkRequest } from "./slink_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service slink.service.v1.ShortLinkService
 */
export const ShortLinkService = {
  typeName: "slink.service.v1.ShortLinkService",
  methods: {
    /**
     * @generated from rpc slink.service.v1.ShortLinkService.CreateShortLink
     */
    createShortLink: {
      name: "CreateShortLink",
      I: CreateShortLinkRequest,
      O: CreateShortLinkReply,
      kind: MethodKind.Unary,
    },
  }
};

