// @generated by protoc-gen-connect-es v1.2.0 with parameter "target=js+dts"
// @generated from file slink/service/v1/user.proto (package slink.service.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { LoginReply, LoginRequest } from "./user_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service slink.service.v1.UserService
 */
export const UserService = {
  typeName: "slink.service.v1.UserService",
  methods: {
    /**
     * @generated from rpc slink.service.v1.UserService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginReply,
      kind: MethodKind.Unary,
    },
  }
};

