version: '3.4'

services:
  slink-frontend:
    image: hominsu/slink:frontend
    container_name: slink-frontend
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      NEXT_GRPC_ENDPOINT: "http://slink-backend:9000"
    ports:
      - "3000:3000"
    networks:
      net:
        aliases:
          - slink-frontend

  slink-backend:
    image: hominsu/slink:backend
    container_name: slink-backend
    depends_on:
      - slink-frontend
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "../app/slink/service/configs:/data/conf"
    ports:
      - "8000:8000"
    networks:
      net:
        aliases:
          - slink-backend

networks:
  net:
    driver: bridge
