// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: slink/service/v1/admin.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListShortLinkRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListShortLinkRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListShortLinkRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListShortLinkRequestMultiError, or nil if none found.
func (m *ListShortLinkRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListShortLinkRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPageSize() <= 0 {
		err := ListShortLinkRequestValidationError{
			field:  "PageSize",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for PageToken

	if len(errors) > 0 {
		return ListShortLinkRequestMultiError(errors)
	}

	return nil
}

// ListShortLinkRequestMultiError is an error wrapping multiple validation
// errors returned by ListShortLinkRequest.ValidateAll() if the designated
// constraints aren't met.
type ListShortLinkRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListShortLinkRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListShortLinkRequestMultiError) AllErrors() []error { return m }

// ListShortLinkRequestValidationError is the validation error returned by
// ListShortLinkRequest.Validate if the designated constraints aren't met.
type ListShortLinkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListShortLinkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListShortLinkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListShortLinkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListShortLinkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListShortLinkRequestValidationError) ErrorName() string {
	return "ListShortLinkRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListShortLinkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListShortLinkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListShortLinkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListShortLinkRequestValidationError{}

// Validate checks the field values on ListShortLinkReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListShortLinkReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListShortLinkReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListShortLinkReplyMultiError, or nil if none found.
func (m *ListShortLinkReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListShortLinkReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListShortLinkReplyMultiError(errors)
	}

	return nil
}

// ListShortLinkReplyMultiError is an error wrapping multiple validation errors
// returned by ListShortLinkReply.ValidateAll() if the designated constraints
// aren't met.
type ListShortLinkReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListShortLinkReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListShortLinkReplyMultiError) AllErrors() []error { return m }

// ListShortLinkReplyValidationError is the validation error returned by
// ListShortLinkReply.Validate if the designated constraints aren't met.
type ListShortLinkReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListShortLinkReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListShortLinkReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListShortLinkReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListShortLinkReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListShortLinkReplyValidationError) ErrorName() string {
	return "ListShortLinkReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListShortLinkReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListShortLinkReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListShortLinkReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListShortLinkReplyValidationError{}

// Validate checks the field values on DeleteShortLinkRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteShortLinkRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteShortLinkRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteShortLinkRequestMultiError, or nil if none found.
func (m *DeleteShortLinkRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteShortLinkRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Key

	if len(errors) > 0 {
		return DeleteShortLinkRequestMultiError(errors)
	}

	return nil
}

// DeleteShortLinkRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteShortLinkRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteShortLinkRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteShortLinkRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteShortLinkRequestMultiError) AllErrors() []error { return m }

// DeleteShortLinkRequestValidationError is the validation error returned by
// DeleteShortLinkRequest.Validate if the designated constraints aren't met.
type DeleteShortLinkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteShortLinkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteShortLinkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteShortLinkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteShortLinkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteShortLinkRequestValidationError) ErrorName() string {
	return "DeleteShortLinkRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteShortLinkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteShortLinkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteShortLinkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteShortLinkRequestValidationError{}
