name: Docker Deploy

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  resolve-registry:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      git_tag: ${{ steps.git_info.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: set-matrix
        run: |
          JSON=$(cat .github/workflows/registry.json | tr '\n' ' ' | sed 's/ //g')
          echo "::set-output name=matrix::$JSON"

      - id: git_info
        run: |
          tag=$(echo ${{ github.ref }} | rev | cut -d/ -f1 | rev)
          echo "::set-output name=tag::$tag"

  docker:
    runs-on: ubuntu-latest
    needs: resolve-registry
    environment:
      name: production_environment
    strategy:
      matrix: ${{fromJSON(needs.resolve-registry.outputs.matrix)}}
    env:
      id: ${{ secrets[matrix.id] }}
      token: ${{ secrets[matrix.token] }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into Registry ${{ matrix.name }}
        uses: docker/login-action@v2
        with:
          registry: ${{ matrix.register }}
          username: ${{ env.id }}
          password: ${{ env.token }}

      - name: Set Up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Set Up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Build and Push ${{ matrix.name }}
        run:
          REPO=${{ matrix.push_link }} VERSION=${{ needs.resolve-registry.outputs.git_tag }} docker buildx bake --file deploy/docker-compose/docker-bake.hcl --push

  release:
    runs-on: ubuntu-latest
    needs: [ docker ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true